services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: streaming
    user: "1000:1000"
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: streaming_nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  frontend:
    image: node:22-alpine
    container_name: vue_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"

  db:
    image: postgres:16-alpine
    container_name: stream
    environment:
      POSTGRES_DB: stream
      POSTGRES_USER: stream
      POSTGRES_PASSWORD: stream
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: